
import pyautogui
import time

time.sleep(10)
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("30004")
pyautogui.press('enter')
pyautogui.typewrite("cust2")
pyautogui.press('enter')
pyautogui.typewrite("77*&FFaa7")
pyautogui.press('enter')
pyautogui.typewrite("30004")
pyautogui.press('enter')
pyautogui.typewrite("cust2")
pyautogui.press('enter')
pyautogui.typewrite("TT*&21tt")
pyautogui.press('enter')
pyautogui.typewrite("30004")
pyautogui.press('enter')
pyautogui.typewrite("cust3")
pyautogui.press('enter')
pyautogui.typewrite("77*&FFaa")
pyautogui.press('enter')
pyautogui.press('enter')

pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("30005")
pyautogui.press('enter')
pyautogui.typewrite("cust2")
pyautogui.press('enter')
pyautogui.typewrite("77*&FFaa")
pyautogui.press('enter')
pyautogui.typewrite("30004")
pyautogui.press('enter')
pyautogui.typewrite("cust2")
pyautogui.press('enter')
pyautogui.typewrite("77*&FFaa")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("4")
pyautogui.press('enter')
pyautogui.typewrite("80004")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("60001")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("80020")
pyautogui.press('enter')

pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("Funny Noises are coming from the unit!")
pyautogui.press('enter')
pyautogui.typewrite("Funny Noise!")
pyautogui.press('enter')
pyautogui.typewrite("When it turns on it screams at me and it's quite offending.")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("4")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("80004")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("80020")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("I'm so confused.")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("Double broken!")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("60001")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("N")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("80600")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("Never mind, I oiled it and all is fine now.")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("4")
pyautogui.press('enter')
pyautogui.typewrite("80600")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("30530")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("80600")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("4")
pyautogui.press('enter')
pyautogui.typewrite("80020")
pyautogui.press('enter')

pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("50008")
pyautogui.press('enter')
pyautogui.typewrite("agentJ")
pyautogui.press('enter')
pyautogui.typewrite("TT*&21tt")
pyautogui.press('enter')

pyautogui.typewrite("11")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("12")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("1")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("34063")
pyautogui.press('enter')
pyautogui.typewrite("y")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("C")
pyautogui.press('enter')
pyautogui.typewrite("NobodyWillKnowMe")
pyautogui.press('enter')
pyautogui.typewrite("Nobody Will Know Me")
pyautogui.press('enter')
pyautogui.typewrite("No Body")
pyautogui.press('enter')
pyautogui.typewrite("HarryHorse")
pyautogui.press('enter')
pyautogui.typewrite("Horse and goat and donkey get along")
pyautogui.press('enter')
pyautogui.typewrite("Nay to Hay")
pyautogui.press('enter')
pyautogui.typewrite("abcdefg")
pyautogui.press('enter')
pyautogui.typewrite("aaJJ88$#a")
pyautogui.press('enter')
pyautogui.typewrite("aJJ77$#J")
pyautogui.press('enter')
pyautogui.typewrite("aaJ99$#c")
pyautogui.press('enter')
pyautogui.typewrite("aaJJ8$#@")
pyautogui.press('enter')
pyautogui.typewrite("aaJJ77*(")
pyautogui.press('enter')
pyautogui.typewrite("aaJJ88$#")
pyautogui.press('enter')
pyautogui.typewrite("2004")
pyautogui.press('enter')
pyautogui.typewrite("1910")
pyautogui.press('enter')
pyautogui.typewrite("2003")
pyautogui.press('enter')
pyautogui.typewrite("asdf")
pyautogui.press('enter')
pyautogui.typewrite("-8.22")
pyautogui.press('enter')
pyautogui.typewrite("0.00")
pyautogui.press('enter')
pyautogui.typewrite("125000.12")
pyautogui.press('enter')
pyautogui.typewrite("Not all countries get along unfortunately")
pyautogui.press('enter')
pyautogui.typewrite("u.s.a.")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("53070")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("c")
pyautogui.press('enter')
pyautogui.typewrite("C")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("Wylie Coyote")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("dd99@$FF")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("180222.22")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("canada")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("5")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("6")
pyautogui.press('enter')
pyautogui.typewrite("80599")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("7")
pyautogui.press('enter')
pyautogui.typewrite("70533")
pyautogui.press('enter')

pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("8")
pyautogui.press('enter')
pyautogui.typewrite("64611")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("20020")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("4")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("5")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("7")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("8")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("C")
pyautogui.press('enter')
pyautogui.typewrite("CrazyCamel")
pyautogui.press('enter')
pyautogui.typewrite("Sandy Sand")
pyautogui.press('enter')
pyautogui.typewrite("12RR!@jj")
pyautogui.press('enter')
pyautogui.typewrite("1911")
pyautogui.press('enter')
pyautogui.typewrite("54321.22")
pyautogui.press('enter')
pyautogui.typewrite("Australia")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("5")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("9")
pyautogui.press('enter')
pyautogui.typewrite("80600")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("N")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("8")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("9")
pyautogui.press('enter')
pyautogui.typewrite("80600")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("Enjoy your purchase!")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("Ticket is now closed.")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("8")
pyautogui.press('enter')
pyautogui.typewrite("80600")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("9")
pyautogui.press('enter')
pyautogui.typewrite("70533")
pyautogui.press('enter')
pyautogui.typewrite("1")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("9")
pyautogui.press('enter')
pyautogui.typewrite("80204")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("N")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("9")
pyautogui.press('enter')
pyautogui.typewrite("80020")
pyautogui.press('enter')
pyautogui.typewrite("2")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("9")
pyautogui.press('enter')
pyautogui.typewrite("70533")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("9")
pyautogui.press('enter')
pyautogui.typewrite("60001")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("N")
pyautogui.press('enter')
pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("7")
pyautogui.press('enter')
pyautogui.typewrite("60001")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')

pyautogui.typewrite("10")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("30001")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("50599")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("30004")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("34000")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("53007")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("30014")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("70021")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("35035")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("82042")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("35049")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("3")
pyautogui.press('enter')
pyautogui.typewrite("54056")
pyautogui.press('enter')
pyautogui.typewrite("Y")
pyautogui.press('enter')

pyautogui.press('enter')

pyautogui.typewrite("5")
pyautogui.press('enter')
pyautogui.press('enter')

pyautogui.typewrite("11")
pyautogui.press('enter')
pyautogui.press('enter')

pyautogui.typewrite("12")
pyautogui.press('enter')
pyautogui.press('enter')

pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("0")
pyautogui.press('enter')
pyautogui.typewrite("y")
pyautogui.press('enter')
